branches:
  only:
  - master
sudo: false
language: ruby
cache: bundler
install:
- git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
- cd $TRAVIS_REPO_SLUG
- git checkout -qf $TRAVIS_BRANCH
- git config user.email "systems+crunchbot@crunch.io"
- git config user.name "Crunchbot"
- bundle install
script:
- ./build.sh
env:
  global:
    secure: i6joWUeXKn5/qIU8fJcuaGMvzlTksPvzY012oHyxYe5JfegtSwwjSrmA1atRSwOBH37+7irWq0En+iUdTujkypH9Oh4l25cESmNCM7vS7s/8acBjQjkSxH9eSB3cmOqbP1E77cKu+2zEDZKjvKN50jO37SVbG5DdsqF+gCriG0pv0rqS8kARn4jbtf6q4JlG3EyMHUMGvEuxusLc0/O7MYNxD42+AdDk7hdDeI1nGuFWJR5yGN8b/gpnLcAjyFR6naz5tdov5gWsWDMRN4DRqbe2tK1eGJlF3W1xt7D0cTxnR9Vm2Pijeh2z3XuvjljDB6BxsoWZHfr+4zRg0T6yGO3IOAD+JgX+gkuE6+jxLSRnY5NRzyZkvtMKQcrNwyHeFrACO1RJx+lMgLTliqhjwLImEzvRgE0uVdmVr3mtxs11QqP3mvFcXk3P9o9X+7oDLyWV136IrUYnh55fqt4SVU3/rHCao/sT0cmub8gxSVWi4SIMfaNYFNsFsSIYy/qOASmdvqvSwUumL15QOmSWefVfpG5TUAh7OlCxgjc9ChheHVl72MCN4CDlSt3QfV1jRVHt7E1rfdAozdBu1CuDiOwopkeEffKTt2mFy39QUAbJyhuNA0iJqTlrhXso9wR+BvOKhZwvnWiosA56A49b9cQcu6AGiLXmmon/XXC5yes=
