site_name: Clinical Research FHIR Guide
theme:
  name: material
  # logo: assets/logo-arrow-sans-medium-black.svg
  logo: assets/msk-logo.svg
extra_css:
  - stylesheets/extra.css
copyright: Copyright &copy; 2022 MSK
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/memorialsloankettering/
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/memorialsloankettering
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MSKCancerCenter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/mskcc
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/memorial-sloan-kettering-cancer-center/mycompany/

nav:
  - Home: index.md
  - Authentication: authentication.md
  - Searching: searching.md
  - Pagination: pagination.md
  - "Available Resources":
      - "Adverse Event": resources/adverse-event.md
      - "Diagnostic Report (Response)": resources/diagnostic-report.md
      - "Group": resources/group.md
      - "Patient (Demographics)": resources/patient.md
      - "Medication Statement": resources/medications.md
      - "Observation (Labs)": resources/lab-result.md
      - "Observation (Vitals)": resources/vital-sign.md
      - "Observation (Response Imaging)": resources/imaging.md
  - Structure Definitions: structure-definitions.md
  - Errors: errors.md
  - "Release Notes": release-notes.md
  - "Contact Us": contact-us.md
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
